name: 'Setup Docker Image'
description: 'Build or reassemble from cache (if previously built) a docker image'

inputs:
  image-name:
    description: 'The name to use for created image'
    required: true
    default: 'app'
  load-image:
    description: 'Whether or not to load the image after creation'
    required: true
    default: true
  target:
    description: 'The build step target of the docker image'
  build-args:
    description: "Build args for docker build"

outputs:
  image-name:
    description: "The name of the created image"
    value: ${{ inputs.image-name }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and export
      uses: docker/build-push-action@v4
      with:
        context: .
        target: ${{ inputs.target }}
        tags: ${{ inputs.image-name }}:latest
        load: ${{ inputs.load-image }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: ${{ inputs.build-args }}
