#!/usr/bin/env bash
#
# Regenerates all generated code files, then
# copies (used with custom merge strategies).
# To use, add a merge strategy to .git/config
# with the following driver:
# driver = ./.gitmerge/codegen <generated_path> %A
#

set -euo pipefail
IFS=$'\n\t'
PATH=$(npm bin):$PATH

./script/generate-component-index

cp "$1" "$2"
