version: '3.4'

services:
    app:
        build:
           context: .
           target: test
        command: "dev-serve"
        environment:
            # Pallet
            DEVNAME: docker
            ENVIRONMENT: dev

            # Ask Izzy
            STRAPI_URL: "https://cms-askizzy.docker.dev"
            SCREENSHOT_FAILURES: 1
            PAUSE_AFTER_FAIL: 1
            GOOGLE_ANALYTICS_URL: "https://google-analytics.docker.dev"
            PROXY_DOMAINS: '{"fonts.typography.com":"typography-com.docker.dev", "www.googletagmanager.com":"gtagmanager.docker.dev", "maps.googleapis.com":"gmaps.docker.dev", "maps.gstatic.com":"gmaps-static.docker.dev", "csi.gstatic.com":"gcsi-static.docker.dev", "fonts.gstatic.com":"gfonts-static.docker.dev", "tagmanager.google.com":"gtagmanager.docker.dev", "fonts.google.com":"gfonts.docker.dev", "www.google-analytics.com":"google-analytics.docker.dev", "google-analytics.com":"google-analytics.docker.dev", "bam.nr-data.net":"bam-nr-data.docker.dev", "js-agent.newrelic.com":"js-agent-newrelic.docker.dev",}'
            NEW_RELIC_CONFIG: '{}'
            NEW_RELIC_INFO: '{}'

            NODE_ENV: development
        ports:
            - '8000:8000'
            - '8001:8001'
        volumes:
            - .:/app
            - ./public/static:/static # Useful for testing prod setup
