version: '3.4'

services:
    app:
        build:
           context: .
           target: test
        command: "dev-serve"
        environment:
            # Pallet
            DEVNAME: docker
            ENVIRONMENT: dev
            SCREENSHOT_FAILURES: 1
            PAUSE_AFTER_FAIL: 1
        ports:
            - '80:8000'
            - '8000:8000'
            - '8001:8001'
        volumes:
            - .:/app
