version: "3.4"

services:
  app:
    build:
      context: .
      target: development
    platform: linux/amd64
    environment:
      SITE_PROTOCOL: "http"
      SITE_DOMAIN: "localhost"
      PAUSE_AFTER_FAIL: 1
      STATIC_PAGE_REGENERATION_SECRET: "hunter2"
      STATIC_PAGE_PREVIEW_SECRET: "hunter2"
      ENVIRONMENT: "local development"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - .cache:/tmp/home/.cache
