version: "3.4"

services:
  app:
    build:
      context: .
      args:
        - VERSION=emulated-production
    command: "shell bash -c 'yarn run deploy && yarn run serve'"
    environment:
      STATIC_PAGE_REGENERATION_SECRET: "hunter2"
      STATIC_PAGE_PREVIEW_SECRET: "hunter2"
      ENVIRONMENT: "emulated production"
      SITE_PROTOCOL: "https"
      SITE_DOMAIN: "askizzy.org.au"
      HTTP_PROXY: "http://http-proxy:8888"
    volumes:
      - ./.env.production.local:/app/.env.production.local
      - storage:/storage

  load-balancer:
    image: nginx
    volumes:
      - ./config/nginx-emulate-production.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    ports:
      - "8000:8000"

  http-proxy:
    image: vimagick/tinyproxy
    command: sh -c "sed -i -e 's/^LogLevel.*/LogLevel Warning/' /etc/tinyproxy/tinyproxy.conf && tinyproxy -d"
    restart: unless-stopped

volumes:
  storage:
