version: '3.4'

services:
    app:
        build:
           context: .
           target: test
        command: "dev-serve"
        environment:
            # Pallet
            DEVNAME: docker
            ENVIRONMENT: dev

            # Ask Izzy
            STRAPI_URL: "https://cms-askizzy.docker.dev"
            SCREENSHOT_FAILURES: 1
            PAUSE_AFTER_FAIL: 1

            NODE_ENV: development
        ports:
            - '8000:8000'
            - '8001:8001'
        volumes:
            - .:/app
            - ./public/static:/static # Useful for testing prod setup
