/* @flow */
/* Generated by ./script/iconify */
/* eslint-disable max-len */

import React from "react";
import classnames from "classnames";

export default class SvgIconAdvocacy extends React.Component {
    props: {
        className?: string,
    };
    state: void;

    render() {
        const {className, ...rest} = this.props;
        const classes = classnames(
            "AdvocacyIcon",
            "disallow-override-color",
            "Icon",
            "SvgIcon",
            className
        );

        return (
            <span
                {...rest}
                dangerouslySetInnerHTML={{__html: `
                    <svg class='${classes}' id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><title>New-icons</title><rect x="0.57" width="64" height="64" fill="none"></rect><path d="M45.6,9.68,20.44,8.06A12.62,12.62,0,0,0,7,19.84L6.16,33.46A12.61,12.61,0,0,0,17.33,46.8l-1,10.72L31,47.71l12.09.78A12.62,12.62,0,0,0,56.5,36.71l.88-13.62A12.62,12.62,0,0,0,45.6,9.68Z" fill="#9cd6e5"></path><path d="M27.84,18.87a1.15,1.15,0,0,1,1-1.48l2.29-.23a1.18,1.18,0,0,1,1.29,1.25l.2,13.1a1.17,1.17,0,0,1-1.06,1.27,1.15,1.15,0,0,1-1.26-1ZM31.76,35.1a2.19,2.19,0,0,1,2.48,2l0,.32a2.27,2.27,0,0,1-4.52.46l0-.32A2.21,2.21,0,0,1,31.76,35.1Z" fill="#37474f"></path></svg>
                `}}
            />
        );
    }
}
