/* Do not edit - Generated by iconify. See README.md for more details. */
/* eslint-disable max-len */

import BaseIcon from "./BaseIcon.js";


export default class SvgIconBlank extends BaseIcon {
    static defaultProps = {
        iconClass: "BlankIcon",
    }

    svgContent = `
        <svg class='${this.classNames}' xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://creativecommons.org/ns#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" version="1.1" x="0px" y="0px" viewBox="${this.props.viewBox || "0 0 64 64"}" enable-background="new 0 0 64 64"  xml:space="preserve" id="svg4450" sodipodi:docname="askizzy-icon-blank.svg" inkscape:version="0.92.1 r15371"><g></g></svg>
    `;
}
