/* Do not edit - Generated by iconify. See README.md for more details. */
/* eslint-disable max-len */

import BaseIcon from "./BaseIcon.js";


export default class SvgIconCensus2016 extends BaseIcon {
    static defaultProps = {
        iconClass: "Census2016Icon",
    }

    svgContent = `
        <svg class='${this.classNames}' version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="${this.props.viewBox || "0 0 100 100"}"><style type="text/css">
    `;
}
