/* @flow */
/* Do not edit - Generated by iconify. See README.md for more details. */
/* eslint-disable max-len */

import BaseIcon from "./BaseIcon";

export default class SvgIconChat extends BaseIcon {
    static defaultProps = {
        iconClass: "ChatIcon",
    }

    svgContent = `
        <svg class='${this.classNames}' xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://creativecommons.org/ns#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 17 17.707108" version="1.1" ><metadata id="metadata1655"><rdf:RDF><cc:Work rdf:about><dc:format>image/svg+xml</dc:format><dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"></dc><dc:title> speech bubbles </dc:title></cc:Work></rdf:RDF></metadata><defs id="defs1653"></defs><title id="title1641"> speech bubbles </title><g fill="#36c" id="g1647" fill="none" stroke="#ffffff" stroke-opacity="1" transform="translate(0.5,0.5)"><path d="M 14,0 H 2 A 2,2 0 0 0 0,2 v 14 l 4,-4 h 10 a 2,2 0 0 0 2,-2 V 2 A 2,2 0 0 0 14,0 Z" id="path1645" fill="none" stroke="#ffffff" stroke-opacity="1"></path></g></svg>
    `;
}
