/* @flow */
/* jscs: disable */
/* This code is generated by ./script/iconify - do not edit. */

import React from "react";
import mui from "material-ui";

export default class SvgIconCheckboxSelected extends React.Component {

    render(): ReactElement {
        return (
            <mui.SvgIcon
                {...this.props}
                className={ `${this.props.className || ''} CheckboxSelectedIcon Icon` }
                viewBox="0 0 64 64"
                dangerouslySetInnerHTML={{__html: `<path d='M44.38,47.476H20.086c-1.967,0-3.562-1.595-3.562-3.562V19.619   c0-1.709,1.386-3.095,3.095-3.095h24.761c1.709,0,3.095,1.386,3.095,3.095v24.762C47.476,46.09,46.09,47.476,44.38,47.476z    M29.902,37.531l9.506-9.506c0.43-0.43,0.43-1.126,0-1.556c-0.428-0.43-1.127-0.43-1.555,0l-8.729,8.728l-3.096-3.095   c-0.43-0.43-1.126-0.43-1.556,0c-0.429,0.43-0.429,1.126,0.001,1.556l3.873,3.873c0.215,0.215,0.496,0.322,0.777,0.322   S29.688,37.746,29.902,37.531z' id='XMLID_679_' style='fill:#231F20;'/>`}}
            >

            </mui.SvgIcon>
        );
    }

}
