/* @flow */
/* jscs: disable */
/* This code is generated by ./script/iconify - do not edit. */

import React from "react";
import mui from "material-ui";

export default class SvgIconChevronBack extends React.Component {

    render(): React.Component {
        return (
            <mui.SvgIcon
                {...this.props}
                className={ this.props.className + " ChevronBack"}
                viewBox="0 0 64 64"
            >
            <path d='M37.929,19.043c0.281,0,0.563,0.107,0.777,0.322c0.43,0.429,0.43,1.126,0,1.555l-11.08,11.081    l11.08,11.079c0.43,0.43,0.43,1.127,0.001,1.556c-0.43,0.43-1.126,0.429-1.556,0.001L25.293,32.779    c-0.207-0.207-0.322-0.486-0.322-0.778s0.115-0.571,0.322-0.777l11.858-11.858C37.366,19.15,37.648,19.043,37.929,19.043z'/>
            </mui.SvgIcon>
        );
    }

}
