/* @flow */
/* Generated by ./script/iconify */
/* eslint-disable max-len */


import BaseIcon from "./BaseIcon";

export default class SvgIconCrossColor extends BaseIcon {
    static defaultProps = {
        iconClass: "CrossColorIcon",
    }

    get svgContent(): string {
        return `
            <svg class='${this.classNames}' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12.89 13.28"><title>Cross</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><polygon points="12.89 2 10.8 0 6.44 4.55 2.09 0 0 2 4.44 6.64 0 11.28 2.09 13.28 6.44 8.73 10.8 13.28 12.89 11.28 8.45 6.64 12.89 2" fill="#f48267"></polygon></g></g></svg>
        `;
    }
}
