/* @flow */
/* Do not edit - Generated by iconify. See README.md for more details. */
/* eslint-disable max-len */
import type { ElementConfig as ReactElementConfig } from "react"

import BaseIcon from "./BaseIcon";

export default class SvgIconDemographicFamilyViolence extends BaseIcon {
    static defaultProps: ReactElementConfig<typeof BaseIcon> = {
        iconClass: "DemographicFamilyViolenceIcon",
    }

    svgContent: string = `
        <svg class='${this.classNames}' viewbox="0 0 64 64" xmlns="http://www.w3.org/2000/svg"><g><rect height="64" fill="none" width="64"></rect><path d="M58.19,35a5.56,5.56,0,0,0-2.33-3.7,5.25,5.25,0,0,0-4-1,5.56,5.56,0,0,0-3.71,2.35l-1.9,2.72L41.51,8.68a4.27,4.27,0,1,0-8.41,1.49L36,26.26c0,.23,0,.32-.25.36s-.32,0-.36-.25l-3.53-20A4.27,4.27,0,1,0,23.41,7.9l3.53,20c0,.23,0,.32-.25.36a.35.35,0,0,1-.25,0,.35.35,0,0,1-.11-.23L23.26,10.58a4.27,4.27,0,1,0-8.41,1.49l3.08,17.38c0,.23,0,.32-.25.36s-.32,0-.36-.25l-1.71-9.66A4.27,4.27,0,1,0,7.2,21.39l5.36,30.26a11.51,11.51,0,0,0,11.28,9.46,11.53,11.53,0,0,0,2-.18l14.42-2.55A9.8,9.8,0,0,0,46.09,55l.11.08L57.19,39a5.26,5.26,0,0,0,1-4" fill="#ffcc80"></path><path d="M35.38,23l-.5.71.11.65.71.5L35.38,23m12.29-4.49-3.52,5,1.46,8.23,2.13,1.49.41-.59a5.57,5.57,0,0,1,3.44-2.3l-4.45-3.11,4.28-6.13-3.75-2.62" fill="#f6695e"></path><path d="M51.58,30.38a5.57,5.57,0,0,0-3.44,2.3l-.41.59,3,2.07,2.62-3.75-1.73-1.21m-16.7-6.66-.27.38.38.27-.11-.65m2.36-3.37L35.38,23l.33,1.86,5.05,3.53-4.33,6.19,3.75,2.62L44.51,31l1.09.76-1.46-8.23-.76,1.09-6.15-4.3" fill="#f65e45"></path></g></svg>
    `;
}
