/* @flow */
/* Generated by ./script/iconify */
/* eslint-disable max-len */

import React from "react";
import classnames from "classnames";

export default class SvgIconDemographicParole extends React.Component {
    props: {
        className?: string,
    };
    state: void;

    render() {
        const {className, ...rest} = this.props;
        const classes = classnames(
            "DemographicParoleIcon",
            "disallow-override-color",
            "Icon",
            "SvgIcon",
            className
        );

        return (
            <span
                {...rest}
                dangerouslySetInnerHTML={{__html: `
                    <svg class='${classes}' id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><title>New-icons</title><rect x="0.57" width="64" height="64" fill="none"></rect><path d="M35.56,48.93a2.82,2.82,0,0,0-1.94-3.48L13.31,39.66A2.82,2.82,0,0,0,9.83,41.6a2.81,2.81,0,0,0-3.48,1.93L5.2,47.59l31.14,8.88,1.16-4.06A2.82,2.82,0,0,0,35.56,48.93Z" fill="#c77600"></path><path d="M57.33,49.7s-25.83-26-27.17-25.21l-1-1a1.41,1.41,0,0,0,0-2l-1-1,2-2h0l-.35-.61a1.4,1.4,0,0,1,.35-1.38,1.56,1.56,0,0,1,1.71-.32,2.18,2.18,0,0,0,.28.18l.07.06,0,0a2.1,2.1,0,0,0,2.69-3.07c0-1.19-1.25-3.29-3.22-5.27s-4.09-3.23-5.27-3.23a2.1,2.1,0,0,0-3.06,2.69l0,0,.06.08a2.06,2.06,0,0,0,.18.28,1.56,1.56,0,0,1-.32,1.71,1.4,1.4,0,0,1-1.49.32l-.49-.31h0l-8,8h0a1.4,1.4,0,0,1,0,2,1.52,1.52,0,0,1-1.61.4,2.1,2.1,0,0,0-3.1,2.79C8.51,23.9,9.75,26,11.73,28S15.81,31.21,17,31.2a2.1,2.1,0,0,0,3.07-2.69l.12.12L20,28.41l0-.09a1.61,1.61,0,0,1,.22-1.83,1.4,1.4,0,0,1,2,0h0l2-2h0l1,1a1.41,1.41,0,0,0,2,0h0l1,1h0c-1.1,1.1,25.21,27.2,25.21,27.2,1.1,1.1,3.88,2.09,5,1S58.43,50.8,57.33,49.7Z" fill="#795548"></path></svg>
                `}}
            />
        );
    }
}
