/* @flow */
/* Generated by ./script/iconify */
/* eslint-disable max-len */

import React from "react";
import classnames from "classnames";

export default class SvgIconDemographicChildren extends React.Component {
    props: {
        className?: string,
    };
    state: void;

    render() {
        const {className, ...rest} = this.props;
        const classes = classnames(
            "DemographicChildrenIcon",
            "disallow-override-color",
            "Icon",
            "SvgIcon",
            className
        );

        return (
            <span
                {...rest}
                dangerouslySetInnerHTML={{__html: `
                    <svg class='${classes}' id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><title>New-icons</title><rect width="64" height="64" fill="none"></rect><rect x="33.77" y="16.24" width="14.2" height="15.91" fill="#c77600"></rect><path d="M55.07,41.94V59H26.67v-17c0-9.8,9.8-11.5,9.8-11.5h8.95C45.27,30.44,55.07,32.14,55.07,41.94Z" fill="#4a8cd3"></path><path d="M32.35,14v6.67A8.53,8.53,0,0,0,36.61,28v2.58s.85,4.69,4.26,4.69,4.26-4.69,4.26-4.69V28a8.53,8.53,0,0,0,4.26-7.36V14C49.39,6.72,32.35,9.28,32.35,14Z" fill="#ffcc80"></path><path d="M40.87,5c-5.4,0-12.78,3.83-12.78,24.14l5.68,2.13V19.22l9.94-5.68L48,17.8V31.29l5.68-3.55c0-7.53-.28-21.3-9.37-21.3L43.43,5Z" fill="#c77600"></path><path d="M24.46,42.08V40.52c0-4.83-11.36-3.12-11.36,0v1.56a1.42,1.42,0,0,0,0,2.84,5.69,5.69,0,0,0,2.84,4.91v2.05a2.57,2.57,0,0,0,2.84,2.84,2.57,2.57,0,0,0,2.84-2.84V49.83a5.69,5.69,0,0,0,2.84-4.91,1.42,1.42,0,0,0,0-2.84Z" fill="#ffcc80"></path><path d="M18.78,33.56c-4.26,0-7.1,3.55-7.1,7.81v2.27l1.42.57V40.66l8.52-2.84,2.84,2.84v3.55l1.42-.57V41.37c0-2.84-.71-5.68-4.26-6.39l-.71-1.42Z" fill="#c77600"></path><path d="M21.62,50.89a2.88,2.88,0,0,1-5.68,0s-7.1,1.28-7.1,8.1H28.72C28.72,52.17,21.62,50.89,21.62,50.89Z" fill="#80deea"></path></svg>
                `}}
            />
        );
    }
}
