/* Do not edit - Generated by iconify. See README.md for more details. */
/* eslint-disable max-len */

import BaseIcon from "./BaseIcon.js";


export default class SvgIconFacilities extends BaseIcon {
    static defaultProps = {
        iconClass: "FacilitiesIcon",
    }

    svgContent = `
        <svg class='${this.classNames}' viewbox="0 0 64 64"><g><rect height="64" fill="none" width="64"></rect><path d="M14.49,4.8c-5.76,0-10.4,9-10.4,20s4.66,20,10.4,20h26.4v-20c0-11,4.66-20,10.4-20H14.49" fill="#90caf9"></path><path d="M52.09,4.8h-.8a5.5,5.5,0,0,1,.8.08V4.8" fill="#bbdefb"></path><path d="M40.89,24.8h0v20H14.49c-5.74,0-10.4-9-10.4-20V59.2a1.51,1.51,0,0,1,1.6-1.6,1.51,1.51,0,0,1,1.6,1.6h1.6a1.51,1.51,0,0,1,1.6-1.6,1.51,1.51,0,0,1,1.6,1.6h1.6a1.51,1.51,0,0,1,1.6-1.6,1.51,1.51,0,0,1,1.6,1.6h1.6a1.6,1.6,0,0,1,3.2,0h1.6a1.6,1.6,0,0,1,3.2,0h1.6a1.6,1.6,0,1,1,3.2,0h1.6a1.6,1.6,0,1,1,3.2,0h1.6a1.6,1.6,0,1,1,3.2,0V24.8" fill="#d4edff"></path><path d="M51.29,4.8H14.49c-5.76,0-10.4,9-10.4,20h0c0,11,4.66,20,10.4,20h26.4v-20h0c0-11,4.66-20,10.4-20" fill="#c9e8fe"></path><path d="M40.89,24.8v20h10.4C45.55,44.8,40.89,35.85,40.89,24.8Z" fill="#bbdefb"></path><path d="M52.09,44.8v-.08a5.46,5.46,0,0,1-.8.08Z" fill="#bbdefb"></path><path d="M52.09,4.88a5.46,5.46,0,0,0-.8-.08c-5.74,0-10.4,9-10.4,20s4.66,20,10.4,20a5.46,5.46,0,0,0,.8-.08c5.37-.79,9.6-9.4,9.6-19.92S57.46,5.67,52.09,4.88Z" fill="#90caf9"></path><path d="M41.05,27.2h0l-.16,17.6h10.4C46,44.8,41.53,37.12,41.05,27.2Z" fill="#42a5f5"></path><ellipse cx="51.29" cy="24.8" rx="3.21" ry="6.21" fill="#42a5f5"></ellipse></g></svg>
    `;
}
