/* @flow */
/* Generated by ./script/iconify */
/* eslint-disable max-len */

import React from "react";
import classnames from "classnames";

export default class SvgIconFacilities extends React.Component {
    props: {
        className?: string,
    };
    state: void;

    render() {
        const {className, ...rest} = this.props;
        const classes = classnames(
            "FacilitiesIcon",
            "disallow-override-color",
            "Icon",
            "SvgIcon",
            className
        );

        return (
            <span
                {...rest}
                dangerouslySetInnerHTML={{__html: `
                    <svg class='${classes}' id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><title>New-icons</title><rect x="0.57" width="64" height="64" fill="none"></rect><path d="M15.07,4.8c-5.76,0-10.4,9-10.4,20s4.66,20,10.4,20h26.4v-20c0-11,4.66-20,10.4-20H15.07" fill="#90caf9"></path><path d="M52.67,4.8h-.8a5.5,5.5,0,0,1,.8.08V4.8" fill="#bbdefb"></path><path d="M41.47,24.8h0v20H15.07c-5.74,0-10.4-9-10.4-20V59.2a1.51,1.51,0,0,1,1.6-1.6,1.51,1.51,0,0,1,1.6,1.6h1.6a1.51,1.51,0,0,1,1.6-1.6,1.51,1.51,0,0,1,1.6,1.6h1.6a1.51,1.51,0,0,1,1.6-1.6,1.51,1.51,0,0,1,1.6,1.6h1.6a1.6,1.6,0,0,1,3.2,0h1.6a1.6,1.6,0,0,1,3.2,0h1.6a1.6,1.6,0,1,1,3.2,0h1.6a1.6,1.6,0,1,1,3.2,0h1.6a1.6,1.6,0,1,1,3.2,0V24.8" fill="#d4edff"></path><path d="M51.87,4.8H15.07c-5.76,0-10.4,9-10.4,20h0c0,11,4.66,20,10.4,20h26.4v-20h0c0-11,4.66-20,10.4-20" fill="#c9e8fe"></path><path d="M41.47,24.8v20h10.4C46.12,44.8,41.47,35.85,41.47,24.8Z" fill="#bbdefb"></path><path d="M52.67,44.8v-.08a5.46,5.46,0,0,1-.8.08Z" fill="#bbdefb"></path><path d="M52.67,4.88a5.46,5.46,0,0,0-.8-.08c-5.74,0-10.4,9-10.4,20s4.66,20,10.4,20a5.46,5.46,0,0,0,.8-.08c5.37-.79,9.6-9.4,9.6-19.92S58,5.67,52.67,4.88Z" fill="#90caf9"></path><path d="M41.63,27.2h0l-.16,17.6h10.4C46.59,44.8,42.11,37.12,41.63,27.2Z" fill="#42a5f5"></path><ellipse cx="51.87" cy="24.8" rx="3.21" ry="6.21" fill="#42a5f5"></ellipse></svg>
                `}}
            />
        );
    }
}
