/* @flow */
/* Do not edit - Generated by iconify. See README.md for more details. */
/* eslint-disable max-len */
import type { ElementConfig as ReactElementConfig } from "react"

import BaseIcon from "./BaseIcon";

export default class SvgIconHeart extends BaseIcon {
    static defaultProps: ReactElementConfig<typeof BaseIcon> = {
        iconClass: "HeartIcon",
    }

    svgContent: string = `
        <svg class='${this.classNames}' xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://creativecommons.org/ns#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" viewBox="0 0 15 15" xml:space="preserve"><metadata id="metadata9"><rdf:RDF><cc:Work rdf:about><dc:format>image/svg+xml</dc:format><dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"></dc><dc:title></dc:title></cc:Work></rdf:RDF></metadata><defs id="defs7"><marker overflow="visible" id="Arrow1Lstart" refX="0.0" refY="0.0" orient="auto"><path transform="scale(0.8) translate(12.5,0)" fill-rule="evenodd" stroke="#000000" stroke-width="1pt" stroke-opacity="1" fill="#000000" fill-opacity="1" d="M 0.0,0.0 L 5.0,-5.0 L -12.5,0.0 L 5.0,5.0 L 0.0,0.0 z " id="path834"></path></marker></defs><path d="M13.91,6.75c-1.17,2.25-4.3,5.31-6.07,6.94c-0.1903,0.1718-0.4797,0.1718-0.67,0C5.39,12.06,2.26,9,1.09,6.75 C-1.48,1.8,5-1.5,7.5,3.45C10-1.5,16.48,1.8,13.91,6.75z" id="path2" stroke="#ffffff" stroke-opacity="1" fill="none" stroke-width="1" stroke-miterlimit="4" stroke-dasharray="none" stroke-linecap="butt" stroke-linejoin="round"></path></svg>
    `;
}
