/* @flow */
/* Generated by ./script/iconify */
/* eslint-disable max-len */

import React from "react";
import classnames from "classnames";

export default class SvgIconHouse extends React.Component {
    props: {
        className?: string,
    };
    state: void;

    render() {
        const {className, ...rest} = this.props;
        const classes = classnames(
            "HouseIcon",
            "disallow-override-color",
            "Icon",
            "SvgIcon",
            className
        );

        return (
            <span
                {...rest}
                dangerouslySetInnerHTML={{__html: `
                    <svg class='${classes}' id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><title>New-icons</title><rect width="64" height="64" fill="none"></rect><polyline points="57.6 28.44 6.4 28.44 6.4 61.7 39.2 61.7 57.6 61.7 57.6 28.44" fill="#b0deea"></polyline><polyline points="32 2.31 2.03 28.28 2.03 28.44 5.36 28.44 6.4 28.44 6.4 24.73 57.6 27.93 57.6 28.44 58.64 28.44 61.97 28.44 32 2.31" fill="#cc6145"></polyline><polyline points="6.4 24.73 6.4 28.44 57.6 28.44 57.6 27.93 6.4 24.73" fill="#bc5b42"></polyline></svg>
                `}}
            />
        );
    }
}
