/* @flow */
/* Generated by ./script/iconify */
/* eslint-disable max-len */

import SvgIconAddiction from "./Addiction.js";
import SvgIconAdvocacy from "./Advocacy.js";
import SvgIconCentrelink from "./Centrelink.js";
import SvgIconCheckboxSelected from "./CheckboxSelected.js";
import SvgIconCheckboxUnselected from "./CheckboxUnselected.js";
import SvgIconChevronBack from "./ChevronBack.js";
import SvgIconChevron from "./Chevron.js";
import SvgIconClock from "./Clock.js";
import SvgIconCross from "./Cross.js";
import SvgIconDemographicAboriginal from "./DemographicAboriginal.js";
import SvgIconDemographicChildren from "./DemographicChildren.js";
import SvgIconDemographicCouple from "./DemographicCouple.js";
import SvgIconDemographicDisability from "./DemographicDisability.js";
import SvgIconDemographicFamilyViolence from "./DemographicFamilyViolence.js";
import SvgIconDemographicLgbtiq from "./DemographicLgbtiq.js";
import SvgIconDemographicNeedInterpreter from "./DemographicNeedInterpreter.js";
import SvgIconDemographicParole from "./DemographicParole.js";
import SvgIconDemographicPets from "./DemographicPets.js";
import SvgIconDemographicRecentlyArrived from "./DemographicRecentlyArrived.js";
import SvgIconDemographicTorresStrait from "./DemographicTorresStrait.js";
import SvgIconDemographicVeteran from "./DemographicVeteran.js";
import SvgIconEmail from "./Email.js";
import SvgIconEntertainment from "./Entertainment.js";
import SvgIconFacilaties from "./Facilaties.js";
import SvgIconFeedback from "./Feedback.js";
import SvgIconFood from "./Food.js";
import SvgIconHealth from "./Health.js";
import SvgIconHouse from "./House.js";
import SvgIconInfo from "./Info.js";
import SvgIconJob from "./Job.js";
import SvgIconLegal from "./Legal.js";
import SvgIconLoading from "./Loading.js";
import SvgIconLocation from "./Location.js";
import SvgIconLogoLight from "./LogoLight.js";
import SvgIconLogoShadow from "./LogoShadow.js";
import SvgIconLogo from "./Logo.js";
import SvgIconLogotype from "./Logotype.js";
import SvgIconMap from "./Map.js";
import SvgIconMental from "./Mental.js";
import SvgIconMoney from "./Money.js";
import SvgIconPhone from "./Phone.js";
import SvgIconPrint from "./Print.js";
import SvgIconRadioSelected from "./RadioSelected.js";
import SvgIconRadioUnselected from "./RadioUnselected.js";
import SvgIconSearch from "./Search.js";
import SvgIconSkills from "./Skills.js";
import SvgIconSupport from "./Support.js";
import SvgIconTech from "./Tech.js";
import SvgIconThings from "./Things.js";
import SvgIconTick from "./Tick.js";
import SvgIconTram from "./Tram.js";
import SvgIconWalk from "./Walk.js";
import SvgIconWebsite from "./Website.js";

export default {
    Addiction: SvgIconAddiction,
    Advocacy: SvgIconAdvocacy,
    Centrelink: SvgIconCentrelink,
    CheckboxSelected: SvgIconCheckboxSelected,
    CheckboxUnselected: SvgIconCheckboxUnselected,
    ChevronBack: SvgIconChevronBack,
    Chevron: SvgIconChevron,
    Clock: SvgIconClock,
    Cross: SvgIconCross,
    DemographicAboriginal: SvgIconDemographicAboriginal,
    DemographicChildren: SvgIconDemographicChildren,
    DemographicCouple: SvgIconDemographicCouple,
    DemographicDisability: SvgIconDemographicDisability,
    DemographicFamilyViolence: SvgIconDemographicFamilyViolence,
    DemographicLgbtiq: SvgIconDemographicLgbtiq,
    DemographicNeedInterpreter: SvgIconDemographicNeedInterpreter,
    DemographicParole: SvgIconDemographicParole,
    DemographicPets: SvgIconDemographicPets,
    DemographicRecentlyArrived: SvgIconDemographicRecentlyArrived,
    DemographicTorresStrait: SvgIconDemographicTorresStrait,
    DemographicVeteran: SvgIconDemographicVeteran,
    Email: SvgIconEmail,
    Entertainment: SvgIconEntertainment,
    Facilaties: SvgIconFacilaties,
    Feedback: SvgIconFeedback,
    Food: SvgIconFood,
    Health: SvgIconHealth,
    House: SvgIconHouse,
    Info: SvgIconInfo,
    Job: SvgIconJob,
    Legal: SvgIconLegal,
    Loading: SvgIconLoading,
    Location: SvgIconLocation,
    LogoLight: SvgIconLogoLight,
    LogoShadow: SvgIconLogoShadow,
    Logo: SvgIconLogo,
    Logotype: SvgIconLogotype,
    Map: SvgIconMap,
    Mental: SvgIconMental,
    Money: SvgIconMoney,
    Phone: SvgIconPhone,
    Print: SvgIconPrint,
    RadioSelected: SvgIconRadioSelected,
    RadioUnselected: SvgIconRadioUnselected,
    Search: SvgIconSearch,
    Skills: SvgIconSkills,
    Support: SvgIconSupport,
    Tech: SvgIconTech,
    Things: SvgIconThings,
    Tick: SvgIconTick,
    Tram: SvgIconTram,
    Walk: SvgIconWalk,
    Website: SvgIconWebsite,
};
