/* Do not edit - Generated by iconify. See README.md for more details. */
/* eslint-disable max-len */
import SvgIconOnlineSecurity from "@/src/icons/OnlineSecurity.js";
import SvgIconAboriginalFlag from "@/src/icons/AboriginalFlag.js";
import SvgIconAccessibility from "@/src/icons/Accessibility.js";
import SvgIconAddToCompare from "@/src/icons/AddToCompare.js";
import SvgIconAddiction from "@/src/icons/Addiction.js";
import SvgIconAdvocacy from "@/src/icons/Advocacy.js";
import SvgIconBlank from "@/src/icons/Blank.js";
import SvgIconBook from "@/src/icons/Book.js";
import SvgIconCar from "@/src/icons/Car.js";
import SvgIconCensus2016 from "@/src/icons/Census2016.js";
import SvgIconCentrelink from "@/src/icons/Centrelink.js";
import SvgIconChat from "@/src/icons/Chat.js";
import SvgIconCheckboxSelected from "@/src/icons/CheckboxSelected.js";
import SvgIconCheckboxUnselected from "@/src/icons/CheckboxUnselected.js";
import SvgIconChevronBack from "@/src/icons/ChevronBack.js";
import SvgIconChevron from "@/src/icons/Chevron.js";
import SvgIconClock from "@/src/icons/Clock.js";
import SvgIconCrossColor from "@/src/icons/CrossColor.js";
import SvgIconCross from "@/src/icons/Cross.js";
import SvgIconDemographicAboriginal from "@/src/icons/DemographicAboriginal.js";
import SvgIconDemographicAtsi from "@/src/icons/DemographicAtsi.js";
import SvgIconDemographicChildren from "@/src/icons/DemographicChildren.js";
import SvgIconDemographicCouple from "@/src/icons/DemographicCouple.js";
import SvgIconDemographicDisability from "@/src/icons/DemographicDisability.js";
import SvgIconDemographicFamilyViolence from "@/src/icons/DemographicFamilyViolence.js";
import SvgIconDemographicLgbtiq from "@/src/icons/DemographicLgbtiq.js";
import SvgIconDemographicNeedInterpreter from "@/src/icons/DemographicNeedInterpreter.js";
import SvgIconDemographicParole from "@/src/icons/DemographicParole.js";
import SvgIconDemographicPets from "@/src/icons/DemographicPets.js";
import SvgIconDemographicRecentlyArrived from "@/src/icons/DemographicRecentlyArrived.js";
import SvgIconDemographicTorresStrait from "@/src/icons/DemographicTorresStrait.js";
import SvgIconDemographicVeteran from "@/src/icons/DemographicVeteran.js";
import SvgIconEmail from "@/src/icons/Email.js";
import SvgIconEntertainment from "@/src/icons/Entertainment.js";
import SvgIconEscapeViolence from "@/src/icons/EscapeViolence.js";
import SvgIconExperiencingViolence from "@/src/icons/ExperiencingViolence.js";
import SvgIconExternalLink from "@/src/icons/ExternalLink.js";
import SvgIconFacebook from "@/src/icons/Facebook.js";
import SvgIconFacilities from "@/src/icons/Facilities.js";
import SvgIconFeedback from "@/src/icons/Feedback.js";
import SvgIconFood from "@/src/icons/Food.js";
import SvgIconHealth from "@/src/icons/Health.js";
import SvgIconHeart from "@/src/icons/Heart.js";
import SvgIconHouse from "@/src/icons/House.js";
import SvgIconInfo from "@/src/icons/Info.js";
import SvgIconInstagram from "@/src/icons/Instagram.js";
import SvgIconJob from "@/src/icons/Job.js";
import SvgIconLegal from "@/src/icons/Legal.js";
import SvgIconLightning from "@/src/icons/Lightning.js";
import SvgIconLoading from "@/src/icons/Loading.js";
import SvgIconLocation from "@/src/icons/Location.js";
import SvgIconLogoLight from "@/src/icons/LogoLight.js";
import SvgIconLogoShadow from "@/src/icons/LogoShadow.js";
import SvgIconLogo from "@/src/icons/Logo.js";
import SvgIconLogotype from "@/src/icons/Logotype.js";
import SvgIconMap from "@/src/icons/Map.js";
import SvgIconMental from "@/src/icons/Mental.js";
import SvgIconMoney from "@/src/icons/Money.js";
import SvgIconMyList from "@/src/icons/MyList.js";
import SvgIconPencil from "@/src/icons/Pencil.js";
import SvgIconPhoneCalling from "@/src/icons/PhoneCalling.js";
import SvgIconPhoneSolid from "@/src/icons/PhoneSolid.js";
import SvgIconPhoneTalk from "@/src/icons/PhoneTalk.js";
import SvgIconPhone from "@/src/icons/Phone.js";
import SvgIconPlus from "@/src/icons/Plus.js";
import SvgIconPolice from "@/src/icons/Police.js";
import SvgIconPrint from "@/src/icons/Print.js";
import SvgIconQuestionMarkColor from "@/src/icons/QuestionMarkColor.js";
import SvgIconQuestionMark from "@/src/icons/QuestionMark.js";
import SvgIconRadioSelected from "@/src/icons/RadioSelected.js";
import SvgIconRadioUnselected from "@/src/icons/RadioUnselected.js";
import SvgIconRemoveFromCompare from "@/src/icons/RemoveFromCompare.js";
import SvgIconSearch from "@/src/icons/Search.js";
import SvgIconSexualViolence from "@/src/icons/SexualViolence.js";
import SvgIconShare from "@/src/icons/Share.js";
import SvgIconSkills from "@/src/icons/Skills.js";
import SvgIconSupport from "@/src/icons/Support.js";
import SvgIconTech from "@/src/icons/Tech.js";
import SvgIconThings from "@/src/icons/Things.js";
import SvgIconTickColor from "@/src/icons/TickColor.js";
import SvgIconTick from "@/src/icons/Tick.js";
import SvgIconTorresStraitIslandersFlag from "@/src/icons/TorresStraitIslandersFlag.js";
import SvgIconTram from "@/src/icons/Tram.js";
import SvgIconUnder18 from "@/src/icons/Under18.js";
import SvgIconUndo from "@/src/icons/Undo.js";
import SvgIconUsingViolence from "@/src/icons/UsingViolence.js";
import SvgIconWalk from "@/src/icons/Walk.js";
import SvgIconWarning from "@/src/icons/Warning.js";
import SvgIconWebsite from "@/src/icons/Website.js";


export default {
    OnlineSecurity: SvgIconOnlineSecurity,
    AboriginalFlag: SvgIconAboriginalFlag,
    Accessibility: SvgIconAccessibility,
    AddToCompare: SvgIconAddToCompare,
    Addiction: SvgIconAddiction,
    Advocacy: SvgIconAdvocacy,
    Blank: SvgIconBlank,
    Book: SvgIconBook,
    Car: SvgIconCar,
    Census2016: SvgIconCensus2016,
    Centrelink: SvgIconCentrelink,
    Chat: SvgIconChat,
    CheckboxSelected: SvgIconCheckboxSelected,
    CheckboxUnselected: SvgIconCheckboxUnselected,
    ChevronBack: SvgIconChevronBack,
    Chevron: SvgIconChevron,
    Clock: SvgIconClock,
    CrossColor: SvgIconCrossColor,
    Cross: SvgIconCross,
    DemographicAboriginal: SvgIconDemographicAboriginal,
    DemographicAtsi: SvgIconDemographicAtsi,
    DemographicChildren: SvgIconDemographicChildren,
    DemographicCouple: SvgIconDemographicCouple,
    DemographicDisability: SvgIconDemographicDisability,
    DemographicFamilyViolence: SvgIconDemographicFamilyViolence,
    DemographicLgbtiq: SvgIconDemographicLgbtiq,
    DemographicNeedInterpreter: SvgIconDemographicNeedInterpreter,
    DemographicParole: SvgIconDemographicParole,
    DemographicPets: SvgIconDemographicPets,
    DemographicRecentlyArrived: SvgIconDemographicRecentlyArrived,
    DemographicTorresStrait: SvgIconDemographicTorresStrait,
    DemographicVeteran: SvgIconDemographicVeteran,
    Email: SvgIconEmail,
    Entertainment: SvgIconEntertainment,
    EscapeViolence: SvgIconEscapeViolence,
    ExperiencingViolence: SvgIconExperiencingViolence,
    ExternalLink: SvgIconExternalLink,
    Facebook: SvgIconFacebook,
    Facilities: SvgIconFacilities,
    Feedback: SvgIconFeedback,
    Food: SvgIconFood,
    Health: SvgIconHealth,
    Heart: SvgIconHeart,
    House: SvgIconHouse,
    Info: SvgIconInfo,
    Instagram: SvgIconInstagram,
    Job: SvgIconJob,
    Legal: SvgIconLegal,
    Lightning: SvgIconLightning,
    Loading: SvgIconLoading,
    Location: SvgIconLocation,
    LogoLight: SvgIconLogoLight,
    LogoShadow: SvgIconLogoShadow,
    Logo: SvgIconLogo,
    Logotype: SvgIconLogotype,
    Map: SvgIconMap,
    Mental: SvgIconMental,
    Money: SvgIconMoney,
    MyList: SvgIconMyList,
    Pencil: SvgIconPencil,
    PhoneCalling: SvgIconPhoneCalling,
    PhoneSolid: SvgIconPhoneSolid,
    PhoneTalk: SvgIconPhoneTalk,
    Phone: SvgIconPhone,
    Plus: SvgIconPlus,
    Police: SvgIconPolice,
    Print: SvgIconPrint,
    QuestionMarkColor: SvgIconQuestionMarkColor,
    QuestionMark: SvgIconQuestionMark,
    RadioSelected: SvgIconRadioSelected,
    RadioUnselected: SvgIconRadioUnselected,
    RemoveFromCompare: SvgIconRemoveFromCompare,
    Search: SvgIconSearch,
    SexualViolence: SvgIconSexualViolence,
    Share: SvgIconShare,
    Skills: SvgIconSkills,
    Support: SvgIconSupport,
    Tech: SvgIconTech,
    Things: SvgIconThings,
    TickColor: SvgIconTickColor,
    Tick: SvgIconTick,
    TorresStraitIslandersFlag: SvgIconTorresStraitIslandersFlag,
    Tram: SvgIconTram,
    Under18: SvgIconUnder18,
    Undo: SvgIconUndo,
    UsingViolence: SvgIconUsingViolence,
    Walk: SvgIconWalk,
    Warning: SvgIconWarning,
    Website: SvgIconWebsite,
};
