/* Do not edit - Generated by iconify. See README.md for more details. */
/* eslint-disable max-len */

import BaseIcon from "./BaseIcon.js";

export default class SvgIconLightning extends BaseIcon {
    static defaultProps = {
        iconClass: "LightningIcon",
    }

    svgContent = `
        <svg class='${this.classNames}' xmlns="http://www.w3.org/2000/svg" viewBox="${this.props.viewBox || "0 0 24 24"}"><path d="M0 0h24v24H0z" fill="none"></path><path d="M7 2v11h3v9l7-12h-4l4-8z"></path></svg>
    `;
}
