/* @flow */
/* This code is generated by ./script/iconify - do not edit. */
/* eslint-disable max-len */

import React from "react";
import mui from "material-ui";

export default class SvgIconLogoShadow extends React.Component {

    render(): ReactElement {
        return (
            <mui.SvgIcon
                {...this.props}
                className={`${this.props.className || ""} LogoShadowIcon Icon`}
                viewBox="0 0 64 64"
                dangerouslySetInnerHTML={{__html: ``}}
            >

            </mui.SvgIcon>
        );
    }

}
