/* @flow */
/* This code is generated by ./script/iconify - do not edit. */
/* eslint-disable max-len */

import React from "react";
import SvgIcon from "../components/SvgIcon";

export default class SvgIconLogoShadow extends React.Component {

    render(): ReactElement {
        return (
            <SvgIcon
                {...this.props}
                className={`${this.props.className || ""} LogoShadowIcon Icon`}
                viewBox="0 0 64 64"
                dangerouslySetInnerHTML={{__html: `<ellipse cx='32' cy='55.125' rx='26.875' ry='4.125' style=''/>`}}
            />
        );
    }

}
