/* Do not edit - Generated by iconify. See README.md for more details. */
/* eslint-disable max-len */

import BaseIcon from "./BaseIcon.js";

export default class SvgIconPhoneCalling extends BaseIcon {
    static defaultProps = {
        iconClass: "PhoneCallingIcon",
    }

    svgContent = `
        <svg class='${this.classNames}' xmlns="http://www.w3.org/2000/svg" viewBox="${this.props.viewBox || "0 0 64 64"}"><defs><style>.cls-1{fill:none;}.cls-2{fill:#4b5b63;}.cls-3{fill:#a4b6bf;}</style></defs><title>Asset 28</title><g><g><rect class="cls-1" width="64" height="64"></rect><path class="cls-2" d="M4.18,43.71a4,4,0,0,1-.91-2.58,2.8,2.8,0,0,1,1-2.12c.71-.56,8.44-6.37,9.39-7a3.86,3.86,0,0,1,3.77,0c.81.37,3.3,1.6,4.46,2.18a57.46,57.46,0,0,0,6.84-6.74,57.45,57.45,0,0,0,5.9-7.57c-.71-1.09-2.22-3.42-2.68-4.18a3.85,3.85,0,0,1-.46-3.77C32,11,36.86,2.6,37.38,1.79A3.38,3.38,0,0,1,42,1.18c.08,0,7.39,4.73,7.46,7.59C49.72,16.95,42.33,27,36.1,34S20.73,49.51,12.55,50.25H12.5C9.67,50.42,4.24,43.77,4.18,43.71Z" transform="translate(7.25 6.87)"></path><path class="cls-3" d="M13,14.72a1.36,1.36,0,0,1-1-.38L6.15,8.59a1.37,1.37,0,0,1,1.9-2L14,12.37a1.37,1.37,0,0,1-1,2.35Z" transform="translate(7.25 6.87)"></path><path class="cls-3" d="M1.37,24.14a1.37,1.37,0,0,1,0-2.73l8.26-.14h0a1.37,1.37,0,0,1,0,2.73l-8.26.14Z" transform="translate(7.25 6.87)"></path><path class="cls-3" d="M22.21,11a1.37,1.37,0,0,1-1.37-1.34L20.7,1.39A1.37,1.37,0,0,1,22,0h0a1.37,1.37,0,0,1,1.37,1.34l.14,8.26A1.37,1.37,0,0,1,22.23,11Z" transform="translate(7.25 6.87)"></path></g></g></svg>
    `;
}
