/* @flow */
/* Do not edit - Generated by iconify. See README.md for more details. */
/* eslint-disable max-len */
import type { ElementConfig as ReactElementConfig } from "react"

import BaseIcon from "./BaseIcon";

export default class SvgIconPolice extends BaseIcon {
    static defaultProps: ReactElementConfig<typeof BaseIcon> = {
        iconClass: "PoliceIcon",
    }

    svgContent: string = `
        <svg class='${this.classNames}' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><g><rect width="64" height="64" fill="none"></rect><rect x="26.19" y="14.61" width="11.59" height="11.59" transform="translate(-0.03 0.05) rotate(-0.08)" fill="#304885"></rect><rect x="37.8" y="26.19" width="11.59" height="11.59" transform="matrix(1, 0, 0, 1, -0.05, 0.06)" fill="#304885"></rect><rect x="49.4" y="37.76" width="11.59" height="11.59" transform="matrix(1, 0, 0, 1, -0.06, 0.08)" fill="#304885"></rect><rect x="26.22" y="37.8" width="11.59" height="11.59" transform="matrix(1, 0, 0, 1, -0.06, 0.05)" fill="#304885"></rect><rect x="49.37" y="14.58" width="11.59" height="11.59" transform="matrix(1, 0, 0, 1, -0.03, 0.08)" fill="#304885"></rect><rect x="3.01" y="14.65" width="11.59" height="11.59" transform="translate(-0.03 0.01) rotate(-0.08)" fill="#304885"></rect><rect x="14.61" y="26.22" width="11.59" height="11.59" transform="matrix(1, 0, 0, 1, -0.05, 0.03)" fill="#304885"></rect><rect x="3.04" y="37.83" width="11.59" height="11.59" transform="matrix(1, 0, 0, 1, -0.06, 0.01)" fill="#304885"></rect></g></svg>
    `;
}
