/* @flow */
/* Generated by ./script/iconify */
/* eslint-disable max-len */


import BaseIcon from "./BaseIcon";

export default class SvgIconQuestionMarkColor extends BaseIcon {
    static defaultProps = {
        iconClass: "QuestionMarkColorIcon",
    }

    get svgContent(): string {
        return `
            <svg class='${this.classNames}' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10.74 18.18"><title>Asset 2</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path d="M3.8,13.27V11.39a2.61,2.61,0,0,1,.88-2.24L5.91,8C7.08,6.95,7.73,6.16,7.73,4.89A2.24,2.24,0,0,0,5.33,2.6,2.22,2.22,0,0,0,2.89,4.81H0C0,1.72,2.42,0,5.33,0s5.41,1.72,5.41,5c0,2.08-1.28,3.56-2.65,4.86l-.81.78a2.08,2.08,0,0,0-.83,1.77v.88Zm1.33,1.85h0a1.53,1.53,0,0,0-1.53,1.53h0a1.53,1.53,0,0,0,1.53,1.53h0a1.53,1.53,0,0,0,1.53-1.53h0A1.53,1.53,0,0,0,5.12,15.11Z" fill="#a64ab6"></path></g></g></svg>
        `;
    }
}
