/* @flow */
import type {Element} from "React";/* Generated by ./script/iconify */
/* eslint-disable max-len */

import React from "react";
import classnames from "classnames";

type Props = {
    className?: string,
}

export default class SvgIconQuestionMark extends React.Component<Props, void> {

    render(): Element<"span"> {
        const {className, ...rest} = this.props;
        const classes = classnames(
            "QuestionMarkIcon",
            "disallow-override-color",
            "Icon",
            "SvgIcon",
            className
        );

        return (
            <span
                {...rest}
                dangerouslySetInnerHTML={{__html: `
                    <svg class='${classes}' xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" viewBox="0 0 100 100" enable-background="new 0 0 100 100" xml:space="preserve"><path stroke="#000000" stroke-miterlimit="10" d="M63.432,42.424c0-7.41-6.027-13.438-13.438-13.438s-13.438,6.027-13.438,13.438 h3.781c0-5.324,4.332-9.656,9.656-9.656s9.656,4.332,9.656,9.656c0,4.994-3.824,9.066-8.691,9.559h-2.855v13.443h3.781v-9.713 C58.4,54.789,63.432,49.189,63.432,42.424z"></path><rect x="48.104" y="71.205" stroke="#000000" stroke-miterlimit="10" width="3.781" height="3.781"></rect></svg>
                `}}
            />
        );
    }
}
