/* Do not edit - Generated by iconify. See README.md for more details. */
/* eslint-disable max-len */

import BaseIcon from "./BaseIcon.js";


export default class SvgIconRemoveFromCompare extends BaseIcon {
    static defaultProps = {
        iconClass: "RemoveFromCompareIcon",
    }

    svgContent = `
        <svg class='${this.classNames}' viewBox="${this.props.viewBox || "0 0 32 32"}" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="1.33333" y="1.33333" width="29.3333" height="29.3333" stroke="#4C13AE" stroke-width="2.66667"></rect><line x1="25.3333" y1="16" x2="6.66659" y2="16" stroke="#4C13AE" stroke-width="2.66667"></line></svg>
    `;
}
