/* @flow */
/* Generated by ./script/iconify */
/* eslint-disable max-len */

import React from "react";
import classnames from "classnames";

export default class SvgIconSupport extends React.Component {
    props: {
        className?: string,
    };
    state: void;

    render() {
        const {className, ...rest} = this.props;
        const classes = classnames(
            "SupportIcon",
            "disallow-override-color",
            "Icon",
            "SvgIcon",
            className
        );

        return (
            <span
                {...rest}
                dangerouslySetInnerHTML={{__html: `
                    <svg class='${classes}' id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><title>New-icons</title><rect x="0.57" width="64" height="64" fill="none"></rect><path d="M55.55,19.4a3.82,3.82,0,0,0-7.43-1.74l-3.63,14.4-.21-.47L48.58,12a3.82,3.82,0,0,0-7.43-1.74L36.3,29.71l-.2,0L41,7.31a3.82,3.82,0,0,0-7.43-1.74L28,27.78l-.08,0L32.08,8.23a4,4,0,0,0-2.85-4.57,4.05,4.05,0,0,0-4.58,2.83c-.29,1.24-8.16,33.06-8.16,33.06l-4.71-6.92a4.38,4.38,0,0,0-6.7-1.3A5,5,0,0,0,4,38L9.63,49c3.19,5.62,9.27,8.49,13.5,9.48l9.44,2.21a13.08,13.08,0,0,0,15.79-9.56s-.25,1.76,1.68-6.5l5.5-25.23" fill="#ffcc80"></path><path d="M44.38,31.81l.11.25,0-.14-.15-.11m9.18-3.29L50.05,44.64c-1.35,5.79-1.64,6.66-1.68,6.66s0-.16,0-.16A12.59,12.59,0,0,1,47,54.65l.56.33.53.34.42-.47a32.73,32.73,0,0,1,2.59-2.44c4.15-3.69,10.34-9.33,9.32-16.76a8.43,8.43,0,0,0-6.83-7.12" fill="#f886c1"></path><path d="M52,28.39a8.58,8.58,0,0,0-1.16.08,8.43,8.43,0,0,0-5.95,3.8l-.4-.33,0,.14-.11-.25a8.45,8.45,0,0,0-13.46,7.84c1,7.5,8.54,11.21,13.46,13.66q1.49.7,2.58,1.33a12.59,12.59,0,0,0,1.4-3.51s0,.16,0,.16.33-.86,1.68-6.66l3.51-16.11A8.45,8.45,0,0,0,52,28.39" fill="#f8728e"></path></svg>
                `}}
            />
        );
    }
}
