// Generated by ./script/generate-component-index
import BaseQuestion from './personalisation/BaseQuestion';
import Intro from './personalisation/Intro';
import Location from './personalisation/Location';
import Questions from './personalisation/Questions';

export default {
    BaseQuestion: BaseQuestion,
    Intro: Intro,
    Location: Location,
    Questions: Questions,
};
