#!/usr/bin/env bash

# Enable strict mode
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

DEBUG=${DEBUG:-}

# Print commands
PS4='$ $0:$LINENO: '
[ -n "$DEBUG" ] && set -x

PATH=`npm bin`:$PATH

if [ -e node_modules/path ]; then
    BOLD=$(tput bold)
    END=$(tput sgr0)

    echo "You have 'path' in your node_modules, but it's not in package.json anymore."
    echo "Having 'path' installed causes an issue with webpack builds."
    echo "Try ${BOLD}npm prune${END} to remove packages not present in package.json"
    exit 1
fi

echo "Build site with clientside rendering"
webpack \
    --display-error-details \
    $([ -z "$DEBUG" ] && echo -e "--display\nerrors-only") \
    --progress \
    --bail \
    --config ./webpack/prod.load.js

export NODE_ENV=${NODE_ENV:=production}

echo "Build as static site"
script/run-node-script src/server/render-static

echo "Build testing helper script"
webpack \
    --display-error-details \
    $([ -z "$DEBUG" ] && echo -e "--display\nerrors-only") \
    --progress \
    --bail \
    --config webpack/test.config.js
