#!/usr/bin/env bash

# Enable strict mode
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

DEBUG=${DEBUG:-}

# Print commands
PS4='$ $0:$LINENO: '
[ -n "$DEBUG" ] && set -x

PATH=`npm bin`:$PATH

echo "Build site with clientside rendering"
webpack \
    --progress \
    --config ./webpack/prod.load.js

export NODE_ENV=${NODE_ENV:=production}

echo "Build as static site"
script/run-node-script src/server/render-static

echo "Build testing helper script"
webpack \
    --progress \
    --config webpack/test.config.js
