#!/bin/bash

# Replace all external resources in the Google maps API with proxied
# versions, and/or replace with null if a proxy isn't available for that domain
# The google maps file replacements has been moved to nginx + clientside replacements
# The google analytics file remains here for the time being.

declare -A proxy_domains=(
	["gmaps"]="maps.googleapis.com"
	["gmaps-static"]="maps.gstatic.com"
	["gcsi-static"]="csi.gstatic.com"
	["gfonts-static"]="fonts.gstatic.com"
	["gtagmanager"]="tagmanager.google.com"
	["gfonts"]="fonts.google.com"
	["google-analytics"]="www.google-analytics.com"
)

declare -A proxy_dev_domains=(
	["gmaps"]="gmaps.docker.dev"
	["gmaps-static"]="gmaps-static.docker.dev"
	["gcsi-static"]="gcsi-static.docker.dev"
	["gfonts-static"]="gfonts-static.docker.dev"
	["gtagmanager"]="gtagmanager.docker.dev"
	["gfonts"]="gfonts.docker.dev"
	["google-analytics"]="google-analytics.docker.dev"
)

declare -A proxy_prod_domains=(
	["gmaps"]="gmaps.askizzy.org.au"
	["gmaps-static"]="gmaps-static.askizzy.org.au"
	["gcsi-static"]="gcsi-static.askizzy.org.au"
	["gfonts-static"]="gfonts-static.askizzy.org.au"
	["gtagmanager"]="gtagmanager.askizzy.org.au"
	["gfonts"]="gfonts.askizzy.org.au"
	["google-analytics"]="google-analytics.askizzy.org.au"
)

declare -a banned_domains=(
	"cbk0.googleapis.com"
	"cbk1.googleapis.com"
	"mt.googleapis.com"
	"mt0.googleapis.com"
	"mt1.googleapis.com"
	"mts.googleapis.com"
	"mts0.googleapis.com"
	"mts1.googleapis.com"
	"mts0.google.com"
	"mts1.google.com"
	"khm.googleapis.com"
	"khm0.googleapis.com"
	"khm1.googleapis.com"
	"khms.googleapis.com"
	"khms0.googleapis.com"
	"khms1.googleapis.com"
	"khms0.google.com"
	"khms1.google.com"
	"cbks0.googleapis.com"
	"cbks1.googleapis.com"
	"gg.google"
	"g0.gstatic.com"
	"static.panoramio.com.storage.googleapis.com"
	"geo0.ggpht.com"
	"geo1.ggpht.com"
	"geo2.ggpht.com"
	"geo3.ggpht.com"
	"lh3.ggpht.com"
	"lh4.ggpht.com"
	"lh5.ggpht.com"
	"lh6.ggpht.com"
	"safebrowsing.google.com"
	"www.google"
	"maps.google"
	"earthbuilder.googleapis"
)

# Download Google analytics file
GA_FETCH_URL="https://www.google-analytics.com/analytics.js"

if which gsed; then
    SED=gsed
else
    SED=sed
fi

if [ -z "$HTTP_PROXY" ]; then
	wget -O ./public/static/analytics-$(cat public/VERSION).js \
	$GA_FETCH_URL
else
    wget -O ./public/static/analytics-$(cat public/VERSION).js \
    -e use_proxy=yes -e https_proxy=$HTTP_PROXY -e http_proxy=$HTTP_PROXY \
    $GA_FETCH_URL
fi

for var in "${!proxy_domains[@]}"
do
	if [ "$ENVIRONMENT" = "prod" ] || [ "$ENVIRONMENT" = "staging"  ]; then
		$SED -r -i -e \
		"s/${proxy_domains[$var]}/${proxy_prod_domains[$var]}/gi" \
		./public/static/analytics-$(cat public/VERSION).js
	else
		$SED -r -i -e \
		"s/${proxy_domains[$var]}/${proxy_dev_domains[$var]}/gi" \
		./public/static/analytics-$(cat public/VERSION).js
	fi
done
