#!/usr/bin/env node

var fs = require('fs');
var packageJSON = require('../package.json');
var shrinkwrapJSON = require('../npm-shrinkwrap.json');

// Build up an array of dependencies present in each source

// All deps in package.json
var packageDevDeps = Object.keys(packageJSON.devDependencies);
var packageDeps = Object.keys(packageJSON.dependencies).concat(packageDevDeps).sort();

// All deps in npm-shrinkwrap.json
var shrinkwrapDeps = Object.keys(shrinkwrapJSON.dependencies).sort();

// All deps in node_modules
var node_modules = fs.readdirSync("node_modules").sort();
while (node_modules[0][0] === ".") {
    // Remove dotfiles - everything else in node_modules is a module.
    node_modules.splice(0, 1);
}

// Compare the sets of dependencies
compare(shrinkwrapDeps, "npm-shrinkwrap.json", packageDeps, "package.json");
compare(shrinkwrapDeps, "npm-shrinkwrap.json", node_modules, "node_modules");
compare(packageDeps, "package.json", node_modules, "node_modules");

function fail(package, present, missing) {
    console.log("package " + package + " is in " + present + " but not in " + missing);
    process.exit(1);
}

function compare(arr1, name1, arr2, name2) {
    var len = Math.max(arr1.length, arr2.length);
    for (var i = 0; i < len; i++) {
        if (!arr1[i]) {
            fail(arr2[i], name2, name1);
        }
        if (!arr2[i]) {
            fail(arr1[i], name1, name2);
        }
        if (arr1[i] != arr2[i]) {
            if (arr2.indexOf(arr1[i]) > -1) {
                fail(arr2[i], name2, name1);
            } else {
                fail(arr1[i], name1, name2);
            }
        }
    }
}
