#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
PATH=`npm bin`:$PATH

if [ ! -f public/static/env.js ] ; then
    if [ -z "${ISS_URL:=}" ] ; then
        echo "ISS_URL not set and public/static/env.js not present; cannot run."
        exit 1
    fi

    ./script/generate-env-vars > public/static/env.js
fi

if which xdg-open; then
    OPEN=xdg-open
else
    OPEN=open
fi

export PORT=${PORT-8000}
export NODE_ENV=development
export DEBUG=web

(sleep 3; $OPEN http://localhost:$PORT) &

nodemon --watch webpack/ index.js webpack/server &
WEBPACK_PID="$!"

nodemon --watch src/ index &
NODEMON_PID="$!"

trap "kill $NODEMON_PID 2> /dev/null; kill $WEBPACK_PID 2> /dev/null" EXIT

while (kill -0 $NODEMON_PID 2> /dev/null) && (kill -0 $WEBPACK_PID 2> /dev/null)
do
    sleep 1
done

kill $NODEMON_PID 2> /dev/null
kill $WEBPACK_PID 2> /dev/null
