#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
PATH=`npm bin`:$PATH

if [ -z "${ISS_URL:=}" ] ; then
    echo "ISS_URL not set; cannot run."
    exit 1
fi

if which xdg-open; then
    OPEN=xdg-open
else
    OPEN=open
fi

export PORT=${PORT-8000}
export NODE_ENV=development
export DEBUG=web

(sleep 3; $OPEN http://localhost:$PORT) &

node index.js webpack/server &
WEBPACK_PID="$!"

nodemon index &
NODEMON_PID="$!"

trap "kill $NODEMON_PID 2> /dev/null; kill $WEBPACK_PID 2> /dev/null" EXIT

while (kill -0 $NODEMON_PID 2> /dev/null) && (kill -0 $WEBPACK_PID 2> /dev/null)
do
    sleep 1
done
