#!/usr/bin/env bash
set -euxo pipefail
IFS=$'\n\t'
PATH=$(npm bin):$PATH

export NODE_ENV=production
export PORT=8010

./script/test-setup

# Point the app at our mock ISS instance.
ISS_URL="http://localhost:5000/" ./script/recreate-dev-env-file

# we want this quite high as it makes debugging the tests easier.
INTERACTIVE_TIMEOUT="80000"
mocha --compilers js:babel/register --timeout "$INTERACTIVE_TIMEOUT" test/yadda.js $@
