#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
PATH=$(npm bin):$PATH

cat <<JSON
window.ISS_URL = "$ISS_URL";
window.GOOGLE_API_KEY = "$GOOGLE_API_KEY";
window.GOOGLE_ANALYTICS_ID = "${GOOGLE_ANALYTICS_ID:=}"
window.GOOGLE_TAG_MANAGER_ID = "${GOOGLE_TAG_MANAGER_ID:=}";
window.PROXY_TYPOGRAPHY = "${PROXY_TYPOGRAPHY}";
JSON
