#!/usr/bin/env bash

# Enable strict mode
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

VERSION="$(cat public/VERSION)"
STRAPI_URL=${STRAPI_URL:-}
PROXY_DOMAINS=${PROXY_DOMAINS:-}

# Set Strapi url based on env.
if [ -z "$STRAPI_URL" ]; then
	if [ "$ENVIRONMENT" = "prod" ]; then
		if [ "$SITE_DOMAIN" = "beta.askizzy.org.au" ]; then
			STRAPI_URL="https://cms-uat.askizzy.org.au"
		else
			STRAPI_URL="https://cms.askizzy.org.au"
		fi
	fi
	if [ "$ENVIRONMENT" = "staging" ]; then
		STRAPI_URL="https://cms-uat.askizzy.org.au"
	fi
	if [ "$ENVIRONMENT" = "test" ]; then
		STRAPI_URL="https://cms-askizzy-test.docker.dev"
	fi
	if [ "$ENVIRONMENT" = "dev" ] || [ "$ENVIRONMENT" = "development" ]; then
		STRAPI_URL="https://cms-askizzy.docker.dev"
	fi
fi


if [ -z "$PROXY_DOMAINS" ]; then
    if [ "$ENVIRONMENT" = "prod" ] || [ "$ENVIRONMENT" = "staging" ]; then
	    PROXY_DOMAINS="{
            'fonts.typography.com':'typography-com.askizzy.org.au',
            'www.googletagmanager.com':'gtagmanager.askizzy.org.au',
            'maps.googleapis.com':'gmaps.askizzy.org.au',
            'maps.gstatic.com':'gmaps-static.askizzy.org.au',
            'csi.gstatic.com':'gcsi-static.askizzy.org.au',
            'fonts.gstatic.com':'gfonts-static.askizzy.org.au',
            'tagmanager.google.com':'gtagmanager.askizzy.org.au',
            'fonts.google.com':'gfonts.askizzy.org.au',
            'www.google-analytics.com':'google-analytics.askizzy.org.au',
            'google-analytics.com':'google-analytics.askizzy.org.au',
            'bam.nr-data.net':'bam-nr-data.askizzy.org.au',
            'js-agent.newrelic.com':'js-agent-newrelic.askizzy.org.au',
        }"
    else
        PROXY_DOMAINS="{
            'fonts.typography.com':'typography-com.docker.dev',
            'www.googletagmanager.com':'gtagmanager.docker.dev',
            'maps.googleapis.com':'gmaps.docker.dev',
            'maps.gstatic.com':'gmaps-static.docker.dev',
            'csi.gstatic.com':'gcsi-static.docker.dev',
            'fonts.gstatic.com':'gfonts-static.docker.dev',
            'tagmanager.google.com':'gtagmanager.docker.dev',
            'fonts.google.com':'gfonts.docker.dev',
            'www.google-analytics.com':'google-analytics.docker.dev',
            'google-analytics.com':'google-analytics.docker.dev',
            'bam.nr-data.net':'bam-nr-data.docker.dev',
            'js-agent.newrelic.com':'js-agent-newrelic.docker.dev',
        }"
    fi
fi

PROXY_EXCLUDED_DOMAINS="[
    'cbk0.googleapis.com',
	'cbk1.googleapis.com',
	'mt.googleapis.com',
	'mt0.googleapis.com',
	'mt1.googleapis.com',
	'mts.googleapis.com',
	'mts0.googleapis.com',
	'mts1.googleapis.com',
	'mts0.google.com',
	'mts1.google.com',
	'khm.googleapis.com',
	'khm0.googleapis.com',
	'khm1.googleapis.com',
	'khms.googleapis.com',
	'khms0.googleapis.com',
	'khms1.googleapis.com',
	'khms0.google.com',
	'khms1.google.com',
	'cbks0.googleapis.com',
	'cbks1.googleapis.com',
	'gg.google',
	'g0.gstatic.com',
	'static.panoramio.com.storage.googleapis.com',
	'geo0.ggpht.com',
	'geo1.ggpht.com',
	'geo2.ggpht.com',
	'geo3.ggpht.com',
	'lh3.ggpht.com',
	'lh4.ggpht.com',
	'lh5.ggpht.com',
	'lh6.ggpht.com',
	'safebrowsing.google.com',
	'www.google',
	'maps.google',
	'earthbuilder.googleapis'
]"


cat <<JSON
window.ISS_URL = "$ISS_URL";
window.GOOGLE_API_KEY = "$GOOGLE_API_KEY";
window.GOOGLE_ANALYTICS_URL = "${GOOGLE_ANALYTICS_URL:=}";
window.GOOGLE_TAG_MANAGER_ID = "${GOOGLE_TAG_MANAGER_ID:=}";
window.GOOGLE_TAG_MANAGER_AUTH = "${GOOGLE_TAG_MANAGER_AUTH:=}";
window.GOOGLE_TAG_MANAGER_ENV = "${GOOGLE_TAG_MANAGER_ENV:=}";
window.PROXY_DOMAINS = ${PROXY_DOMAINS};
window.PROXY_EXCLUDED_DOMAINS = ${PROXY_EXCLUDED_DOMAINS};
window.PROXY_PROTOCOL = "${PROXY_PROTOCOL:-}";
window.VERSION = "${VERSION}";
window.STRAPI_URL = "$STRAPI_URL";
JSON
