#!/usr/bin/env bash

# Enable strict mode
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

DEBUG=${DEBUG:-}

# Print commands
PS4='$ $0:$LINENO: '
[ -n "$DEBUG" ] && set -x

PATH=$(npm bin):$PATH
CI=${CI:-}
BAIL_ON_TEST_FAIL=${BAIL_ON_TEST_FAIL:-}

export NODE_ENV=production
export PORT=8010
export ENVIRONMENT=development

./script/test-setup

# Point the app at our mock ISS instance.
ISS_URL="http://localhost:5000/"
./script/recreate-dev-env-file

# we want this quite high as it makes debugging the tests easier.
INTERACTIVE_TIMEOUT="20000"
mocha \
    --require @babel/register \
    --require regenerator-runtime/runtime \
    --exit \
    $(([ -n "$CI" ] || [ -n "$BAIL_ON_TEST_FAIL" ]) && echo "--bail") \
    --timeout "$INTERACTIVE_TIMEOUT" \
    test/maps.js $@
