#!/usr/bin/env bash
#
# Mock ISS server on port 5000
#

# Enable strict mode
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

PATH=`npm bin`:$PATH

export NODE_ENV=development
export DEBUG=web

nodemon `dirname $0`/../test/support/mock_iss/index.js
