#!/usr/bin/env bash
set -eo pipefail
IFS=$'\n\t'

conffile=$(mktemp -t nginxconf.XXXXXX)

echo $(pwd)

stripped_iss_host=$(echo $ISS_URL | sed -r "s%//[^0-9]+:[^0-9]+@%//%; s%/$%%")

sed "s%/app/public%$(pwd)/public%g; s%/iss_host/%$stripped_iss_host%g" < conf/nginx.conf > "$conffile"

if [ ! -z "$HTTP_PROXY" ]; then
    PROXY_PLACEHOLDER="#proxy_pass HTTP_PROXY"
    PROXY_VALUE="proxy_pass ${HTTP_PROXY}"

    sed -r -i -e \
    "s%${PROXY_PLACEHOLDER}%${PROXY_VALUE}%gi" \
    $conffile
fi

cat $conffile

nginx -V

nginx -c "$conffile"
