#!/usr/bin/env bash

# Enable strict mode
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

conffile=$(mktemp -t nginxconf.XXXXXX)

echo $(pwd)

export APP_PWD=$(pwd)
export STRIPPED_ISS_HOST=$(echo $ISS_URL | sed -r "s%//[^0-9]+:[^0-9]+@%//%; s%/$%%")

cat conf/nginx.conf > "$conffile"

# Set the nginx csp config
export X_FRAME_OPTIONS="SAMEORIGIN"
export CSP_HEADERS="frame-ancestors 'self'"

echo "$(envsubst '${X_FRAME_OPTIONS} ${CSP_HEADERS} ${STRIPPED_ISS_HOST} ${APP_PWD}' < $conffile)" > "$conffile" 

cat $conffile

nginx -V

nginx -c "$conffile"
