#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
PATH=$PATH:`npm bin`

if which xdg-open; then
    OPEN=xdg-open
else
    OPEN=open
fi

export PORT=${PORT-8080}

(sleep 1; $OPEN http://localhost:$PORT) &
npm run-script dev
