#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
PATH=$PATH:`npm bin`

if which xdg-open; then
    OPEN=xdg-open
else
    OPEN=open
fi

(sleep 1; $OPEN http://localhost:8080) &

forever -w src/server.js
