#!/usr/bin/env bash
set -euxo pipefail
IFS=$'\n\t'
PATH=$(npm bin):$PATH

export NODE_ENV=production
export PORT=8010

# Point the app at the real ISS
./script/recreate-dev-env-file

# Run the unit tests
PAUSE_ON_ERROR= mocha --compilers js:babel/register test/unit.js $@

# Run the search tests
# We pause for 4000ms when ISS rate-limits us, so allow a timeout of 9 seconds
PAUSE_ON_ERROR= mocha --compilers js:babel/register --timeout 9000 test/search.js $@

# Point the app at our mock ISS
ISS_URL="http://localhost:5000/" ./script/recreate-dev-env-file

# build assets if this isn't Travis (which has already)
${CI:=false} || ./script/build-assets

# Saucelabs bails after 90 seconds inactivity,
# but otherwise we want this quite high
# as it makes debugging the tests easier
INTERACTIVE_TIMEOUT="80000"
mocha --compilers js:babel/register --timeout "$INTERACTIVE_TIMEOUT" test/yadda.js $@

# Point the app back at the real ISS
./script/recreate-dev-env-file
