#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
PATH=`npm bin`:$PATH

export NODE_ENV=production
export ISS_URL=http://localhost:5000/

# build assets if this isn't Travis (which has already)
${CI:=false} || ./script/build-assets
# Avoid 8000 locally so it doesn't collide with the dev server
# (we require 8000 for testing else Sauce won't proxy our requests in Safari)
${CI:=false} || export PORT=8010

mocha --timeout 0 --compilers js:babel/register test/*.js "$@"
