#!/usr/bin/env bash
set -euxo pipefail
IFS=$'\n\t'
PATH=$(npm bin):$PATH

export NODE_ENV=production
export PORT=8010
export SPEECH_SERVER_URL=ws://localhost

# Set up the environment variables. If using forklift, these will be
# whatever is specified in your .yaml file, or whatever is passed in
# from the CLI. (See the forklift documentation for details.)
./script/recreate-dev-env-file

# Rebuild the assets if we're not in CI, where the assets have been
# built already.
${CI:=false} || ./script/build-assets
