#!/usr/bin/env bash

# Enable strict mode
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

DEBUG=${DEBUG:-}

# Print commands
PS4='$ $0:$LINENO: '
[ -n "$DEBUG" ] && set -x

PATH=$(npm bin):$PATH

export NODE_ENV=production
export PORT=8010

# Set up the environment variables. If using forklift, these will be
# whatever is specified in your .yaml file, or whatever is passed in
# from the CLI. (See the forklift documentation for details.)
./script/recreate-dev-env-file

# Rebuild the assets if we're not in CI, where the assets have been
# built already.
${CI:=false} || ./script/build-assets
