#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
PATH=`npm bin`:$PATH

BOLD=$(tput bold)
END=$(tput sgr0)

echo "${BOLD}jsonlint${END}"
jsonlint package.json > /dev/null
echo "${BOLD}jsxhint${END}"
jsxhint
echo "${BOLD}jscs${END}"
jscs .
echo "${BOLD}flow${END}"
flow
