#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
PATH=$PATH:`npm bin`

BOLD=$(tput bold)
END=$(tput sgr0)

echo "${BOLD}jsxhint${END}"
jsxhint && echo "Good"
echo "${BOLD}jscs${END}"
jscs .
echo "${BOLD}flow${END}"
flow
