#!/usr/bin/env bash

# Enable strict mode
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

PATH=$(npm bin):$PATH
export NODE_ENV=production
export PORT=8010

PAUSE_ON_ERROR= mocha --require @babel/register test/unit.js $@
