#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
export PATH=`npm bin`:$PATH
export NODE_ENV=production

./script/build-assets

BROWSERS=$( node <<JS
    var fs = require('fs');
    var yaml = require('js-yaml');
    var doc = yaml.safeLoad(fs.readFileSync('./.travis.yml', 'utf8'));
    var i = 0
    for (i = 0; i < doc.env.matrix.length; i++) {
        console.log(doc.env.matrix[i])
    }
JS
)

set +e

for BROWSER in $BROWSERS; do
    # TODO: Move the platform iteration into visual_test.js so we only need one server to go in parallel
    echo "Starting with $BROWSER"
    bash -c "$BROWSER mocha --timeout 0 --compilers js:babel/register test/visual/visual_test.js" $@
    echo "Finished with $BROWSER"
done
