/* @flow */

// Generated by ./script/generate-component-index

import Address from "./components/Address";
import AppBar from "./components/AppBar";
import BrandedFooter from "./components/BrandedFooter";
import ButtonListItem from "./components/ButtonListItem";
import CategoryListItem from "./components/CategoryListItem";
import CollapsedOpeningTimes from "./components/CollapsedOpeningTimes";
import Collapser from "./components/Collapser";
import ContactMethods from "./components/ContactMethods";
import CrisisLineItem from "./components/CrisisLineItem";
import Eligibility from "./components/Eligibility";
import Email from "./components/Email";
import FlatButton from "./components/FlatButton";
import GoogleMapsLink from "./components/GoogleMapsLink";
import HeaderBar from "./components/HeaderBar";
import IconButton from "./components/IconButton";
import Infobox from "./components/Infobox";
import InputListItem from "./components/InputListItem";
import LinkListItem from "./components/LinkListItem";
import ListItem from "./components/ListItem";
import LoadingResultsHeader from "./components/LoadingResultsHeader";
import LogoWithShadow from "./components/LogoWithShadow";
import NavBar from "./components/NavBar";
import OpeningTimes from "./components/OpeningTimes";
import Phone from "./components/Phone";
import ResultListItem from "./components/ResultListItem";
import ResultsList from "./components/ResultsList";
import ResultsMap from "./components/ResultsMap";
import ScreenReader from "./components/ScreenReader";
import ServicePane from "./components/ServicePane";
import SvgIcon from "./components/SvgIcon";
import TextInputListItem from "./components/TextInputListItem";
import TransportTime from "./components/TransportTime";
import ViewOnMapButton from "./components/ViewOnMapButton";
import Web from "./components/Web";

export default {
    Address: Address,
    AppBar: AppBar,
    BrandedFooter: BrandedFooter,
    ButtonListItem: ButtonListItem,
    CategoryListItem: CategoryListItem,
    CollapsedOpeningTimes: CollapsedOpeningTimes,
    Collapser: Collapser,
    ContactMethods: ContactMethods,
    CrisisLineItem: CrisisLineItem,
    Eligibility: Eligibility,
    Email: Email,
    FlatButton: FlatButton,
    GoogleMapsLink: GoogleMapsLink,
    HeaderBar: HeaderBar,
    IconButton: IconButton,
    Infobox: Infobox,
    InputListItem: InputListItem,
    LinkListItem: LinkListItem,
    ListItem: ListItem,
    LoadingResultsHeader: LoadingResultsHeader,
    LogoWithShadow: LogoWithShadow,
    NavBar: NavBar,
    OpeningTimes: OpeningTimes,
    Phone: Phone,
    ResultListItem: ResultListItem,
    ResultsList: ResultsList,
    ResultsMap: ResultsMap,
    ScreenReader: ScreenReader,
    ServicePane: ServicePane,
    SvgIcon: SvgIcon,
    TextInputListItem: TextInputListItem,
    TransportTime: TransportTime,
    ViewOnMapButton: ViewOnMapButton,
    Web: Web,
};
