/* @flow */

// Generated by ./script/generate-component-index

import Accessibility from "./components/Accessibility";
import Address from "./components/Address";
import AppBar from "./components/AppBar";
import BoxedTextDivider from "./components/BoxedTextDivider";
import BoxedText from "./components/BoxedText";
import BrandedFooter from "./components/BrandedFooter";
import ButtonListItem from "./components/ButtonListItem";
import CategoryListItem from "./components/CategoryListItem";
import CollapsedOpeningTimes from "./components/CollapsedOpeningTimes";
import Collapser from "./components/Collapser";
import ContactMethods from "./components/ContactMethods";
import CrisisHeader from "./components/CrisisHeader";
import CrisisLineItem from "./components/CrisisLineItem";
import DebugContainer from "./components/DebugContainer";
import DebugPersonalisation from "./components/DebugPersonalisation";
import DebugQueryScore from "./components/DebugQueryScore";
import DebugSearch from "./components/DebugSearch";
import DebugServiceRecord from "./components/DebugServiceRecord";
import Eligibility from "./components/Eligibility";
import Email from "./components/Email";
import Feedback from "./components/Feedback";
import FlatButton from "./components/FlatButton";
import FloatFromBottom from "./components/FloatFromBottom";
import GeolocationButton from "./components/GeolocationButton";
import GoogleMapsLink from "./components/GoogleMapsLink";
import HeaderBar from "./components/HeaderBar";
import IconButton from "./components/IconButton";
import IndigenousServiceIcon from "./components/IndigenousServiceIcon";
import InputListItem from "./components/InputListItem";
import LinkListItem from "./components/LinkListItem";
import ListItem from "./components/ListItem";
import LgbtiqIcon from "./components/LgbtiqIcon";
import LogoWithShadow from "./components/LogoWithShadow";
import NavBar from "./components/NavBar";
import Ndis from "./components/Ndis";
import OpeningTimes from "./components/OpeningTimes";
import Phone from "./components/Phone";
import ResultListItem from "./components/ResultListItem";
import ResultsList from "./components/ResultsList";
import SitesMap from "./components/SitesMap";
import ScreenReader from "./components/ScreenReader";
import ServiceListIntro from "./components/ServiceListIntro";
import ServicePane from "./components/ServicePane";
import Spacer from "./components/Spacer";
import SvgIcon from "./components/SvgIcon";
import TransportTime from "./components/TransportTime";
import ViewOnMapButton from "./components/ViewOnMapButton";
import Web from "./components/Web";
import OnlineSafetyLink from "./components/OnlineSafetyLink";

export default {
    Accessibility: Accessibility,
    Address: Address,
    AppBar: AppBar,
    BoxedTextDivider: BoxedTextDivider,
    BoxedText: BoxedText,
    BrandedFooter: BrandedFooter,
    ButtonListItem: ButtonListItem,
    CategoryListItem: CategoryListItem,
    CollapsedOpeningTimes: CollapsedOpeningTimes,
    Collapser: Collapser,
    ContactMethods: ContactMethods,
    CrisisHeader: CrisisHeader,
    CrisisLineItem: CrisisLineItem,
    DebugContainer: DebugContainer,
    DebugPersonalisation: DebugPersonalisation,
    DebugQueryScore: DebugQueryScore,
    DebugSearch: DebugSearch,
    DebugServiceRecord: DebugServiceRecord,
    Eligibility: Eligibility,
    Email: Email,
    Feedback: Feedback,
    FlatButton: FlatButton,
    FloatFromBottom: FloatFromBottom,
    GeolocationButton: GeolocationButton,
    GoogleMapsLink: GoogleMapsLink,
    HeaderBar: HeaderBar,
    IconButton: IconButton,
    IndigenousServiceIcon: IndigenousServiceIcon,
    InputListItem: InputListItem,
    LgbtiqIcon: LgbtiqIcon,
    LinkListItem: LinkListItem,
    ListItem: ListItem,
    LogoWithShadow: LogoWithShadow,
    NavBar: NavBar,
    Ndis: Ndis,
    OnlineSafetyLink: OnlineSafetyLink,
    OpeningTimes: OpeningTimes,
    Phone: Phone,
    ResultListItem: ResultListItem,
    ResultsList: ResultsList,
    SitesMap: SitesMap,
    ScreenReader: ScreenReader,
    ServiceListIntro: ServiceListIntro,
    ServicePane: ServicePane,
    Spacer: Spacer,
    SvgIcon: SvgIcon,
    TransportTime: TransportTime,
    ViewOnMapButton: ViewOnMapButton,
    Web: Web,
};
