// Generated by ./script/generate-component-index
import Address from './components/Address';
import AppBar from './components/AppBar';
import CategoryListItem from './components/CategoryListItem';
import CollapsedPhones from './components/CollapsedPhones';
import Collapser from './components/Collapser';
import Eligibility from './components/Eligibility';
import HeaderBar from './components/HeaderBar';
import Infobox from './components/Infobox';
import NavBar from './components/NavBar';
import OpeningTimes from './components/OpeningTimes';
import Phone from './components/Phone';
import ResultListItem from './components/ResultListItem';
import ScreenReader from './components/ScreenReader';
import ServicePane from './components/ServicePane';
import TransportTime from './components/TransportTime';

export default {
    Address: Address,
    AppBar: AppBar,
    CategoryListItem: CategoryListItem,
    CollapsedPhones: CollapsedPhones,
    Collapser: Collapser,
    Eligibility: Eligibility,
    HeaderBar: HeaderBar,
    Infobox: Infobox,
    NavBar: NavBar,
    OpeningTimes: OpeningTimes,
    Phone: Phone,
    ResultListItem: ResultListItem,
    ScreenReader: ScreenReader,
    ServicePane: ServicePane,
    TransportTime: TransportTime,
};
