name: 'Setup Docker Image'
description: 'Build or reassemble from cache (if previously built) a docker image'

outputs:
  app-version:
    description: "The version of the app"
    value: ${{ steps.get-app-version.outputs.app-version }}

runs:
  using: "composite"
  steps:
    - name: Get app version
      id: get-app-version
      shell: bash
      run: echo "app-version=${{ github.ref_name }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Print app version
      shell: bash
      run: 'echo "App version is: ${{ steps.get-app-version.outputs.app-version }}"'
