name: CI

on:
  push:

jobs:
  build-development:
    name: Build - development docker image
    uses: ./.github/workflows/build-docker-image.yaml
    with:
      image-target: development

  build-distribution:
    name: Build - distribution docker image
    uses: ./.github/workflows/build-docker-image.yaml
    needs: build-development
    with:
      target: distribution

  lint-eslint:
    name: Lint - ESLint
    uses: ./.github/workflows/run-in-docker.yaml
    needs: build-development
    with:
      image-target: development
      command: lint-eslint

  lint-flow:
    name: Lint - Flow
    uses: ./.github/workflows/run-in-docker.yaml
    needs: build-development
    with:
      image-target: development
      command: lint-flow

  lint-stylelint:
    name: Lint - Stylelint
    uses: ./.github/workflows/run-in-docker.yaml
    needs: build-development
    with:
      image-target: development
      command: lint-stylelint

  lint-jsonlint:
    name: Lint - JSON Lint
    uses: ./.github/workflows/run-in-docker.yaml
    needs: build-development
    with:
      image-target: development
      command: lint-jsonlint

  lint-hadolint:
    name: Lint - Hadolint
    uses: ./.github/workflows/run-in-docker.yaml
    needs: build-development
    with:
      image-target: development
      command: lint-hadolint

  lint-shellcheck:
    name: Lint - Shellcheck
    uses: ./.github/workflows/run-in-docker.yaml
    needs: build-development
    with:
      image-target: development
      command: lint-shellcheck

  lint-storybook-components:
    name: Lint - storybook components check
    uses: ./.github/workflows/run-in-docker.yaml
    needs: build-development
    with:
      image-target: development
      command: lint-storybook-components

  test-mocha-personalisation:
    name: Test - Mocha - personalisation
    uses: ./.github/workflows/run-in-docker-with-possible-artifact.yaml
    needs: build-development
    with:
      image-target: development
      command: with --test-env --built --mocks test-mocha-personalisation
      docker-path-to-copy-from: /app/testing-screenshots
      host-path-to-copy-to: testing-screenshots

  test-mocha-category-queries:
    name: Test - Mocha - category queries
    uses: ./.github/workflows/run-in-docker-with-possible-artifact.yaml
    needs: build-development
    with:
      image-target: development
      command: with --test-env --built --mocks test-mocha-category-queries
      docker-path-to-copy-from: /app/testing-screenshots
      host-path-to-copy-to: testing-screenshots

  test-mocha-features:
    name: Test - Mocha - features
    uses: ./.github/workflows/run-in-docker-with-possible-artifact.yaml
    needs: build-development
    with:
      image-target: development
      command: with --test-env --built --mocks test-mocha-features
      docker-path-to-copy-from: /app/testing-screenshots
      host-path-to-copy-to: testing-screenshots

  test-mocha-maps:
    name: Test - Mocha - maps
    uses: ./.github/workflows/run-in-docker-with-possible-artifact.yaml
    needs: build-development
    with:
      image-target: development
      command: with --test-env --built --mocks test-mocha-maps
      docker-path-to-copy-from: /app/testing-screenshots
      host-path-to-copy-to: testing-screenshots

  test-mocha-unit:
    name: Test - Mocha - unit
    uses: ./.github/workflows/run-in-docker.yaml
    needs: build-development
    with:
      image-target: development
      command: test-mocha-unit

  deploy:
    name: Deploy - push image to ECR
    uses: ./.github/workflows/push-docker-image-to-ecr.yaml
    needs:
      - build-distribution
      - lint-eslint
      - lint-flow
      - lint-stylelint
      - lint-jsonlint
      - lint-hadolint
      - lint-shellcheck
      - lint-storybook-components
      - test-mocha-personalisation
      - test-mocha-category-queries
      - test-mocha-features
      - test-mocha-maps
      - test-mocha-unit
    with:
      image-target: distribution
      ecr-image-name: ask_izzy
