name: CI

on:
  push:

jobs:
  build-development:
    name: Build - Development
    uses: infoxchange/github-ci/.github/workflows/build-docker-image.yaml@main
    with:
      image-target: development

  build-distribution:
    name: Build - Distribution
    uses: infoxchange/github-ci/.github/workflows/build-docker-image.yaml@main
    needs: build-development
    with:
      image-target: distribution

  lint-eslint:
    name: Lint - ESLint
    uses: infoxchange/github-ci/.github/workflows/run-in-docker.yaml@main
    needs: build-development
    with:
      image-target: development
      command: lint-eslint

  lint-flow:
    name: Lint - Flow
    uses: infoxchange/github-ci/.github/workflows/run-in-docker.yaml@main
    needs: build-development
    with:
      image-target: development
      command: lint-flow

  lint-stylelint:
    name: Lint - Stylelint
    uses: infoxchange/github-ci/.github/workflows/run-in-docker.yaml@main
    needs: build-development
    with:
      image-target: development
      command: lint-stylelint

  lint-jsonlint:
    name: Lint - JSON Lint
    uses: infoxchange/github-ci/.github/workflows/run-in-docker.yaml@main
    needs: build-development
    with:
      image-target: development
      command: lint-jsonlint

  lint-hadolint:
    name: Lint - Hadolint
    uses: infoxchange/github-ci/.github/workflows/run-in-docker.yaml@main
    needs: build-development
    with:
      image-target: development
      command: lint-hadolint
      additional-run-args: -v $(pwd)/Dockerfile:/app/Dockerfile

  lint-shellcheck:
    name: Lint - Shellcheck
    uses: infoxchange/github-ci/.github/workflows/run-in-docker.yaml@main
    needs: build-development
    with:
      image-target: development
      command: lint-shellcheck

  lint-storybook-components:
    name: Lint - Storybook components check
    uses: infoxchange/github-ci/.github/workflows/run-in-docker.yaml@main
    needs: build-development
    with:
      image-target: development
      command: lint-storybook-components

  test-mocha-personalisation:
    name: Test - Mocha personalisation
    uses: infoxchange/github-ci/.github/workflows/run-in-docker-with-possible-artifact.yaml@main
    needs: build-development
    with:
      image-target: development
      command: with --test-env --built --mocks test-mocha-personalisation
      docker-path-to-copy-from: /app/testing-screenshots
      host-path-to-copy-to: testing-screenshots

  test-mocha-category-queries:
    name: Test - Mocha category queries
    uses: infoxchange/github-ci/.github/workflows/run-in-docker-with-possible-artifact.yaml@main
    needs: build-development
    with:
      image-target: development
      command: with --test-env --built --mocks test-mocha-category-queries
      docker-path-to-copy-from: /app/testing-screenshots
      host-path-to-copy-to: testing-screenshots

  test-mocha-features:
    name: Test - Mocha features
    uses: infoxchange/github-ci/.github/workflows/run-in-docker-with-possible-artifact.yaml@main
    needs: build-development
    with:
      image-target: development
      command: with --test-env --built --mocks test-mocha-features
      docker-path-to-copy-from: /app/testing-screenshots
      host-path-to-copy-to: testing-screenshots

  test-mocha-maps:
    name: Test - Mocha maps
    uses: infoxchange/github-ci/.github/workflows/run-in-docker-with-possible-artifact.yaml@main
    needs: build-development
    with:
      image-target: development
      command: with --test-env --built --mocks test-mocha-maps
      docker-path-to-copy-from: /app/testing-screenshots
      host-path-to-copy-to: testing-screenshots

  test-mocha-unit:
    name: Test - Mocha unit
    uses: infoxchange/github-ci/.github/workflows/run-in-docker.yaml@main
    needs: build-development
    with:
      image-target: development
      command: test-mocha-unit

  deploy:
    name: Deploy - Push image to ECR
    uses: infoxchange/github-ci/.github/workflows/push-docker-image-to-ecr.yaml@main
    needs:
      - build-distribution
      - lint-eslint
      - lint-flow
      - lint-stylelint
      - lint-jsonlint
      - lint-hadolint
      - lint-shellcheck
      - lint-storybook-components
      - test-mocha-personalisation
      - test-mocha-category-queries
      - test-mocha-features
      - test-mocha-maps
      - test-mocha-unit
    with:
      image-target: distribution
      ecr-image-name: ask_izzy
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    permissions:
      id-token: write
