name: Run command in docker container

on:
  workflow_call:
    inputs:
      image-target:
        description: 'The build step target of the docker image'
        type: string
      command:
        description: 'The command to run using the built docker image'
        required: true
        type: string
      additional-run-args:
        description: 'Any additional args to pass to the docker run subcommand'
        type: string

jobs:
  run-in-docker:
    name: Run cmd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get app version
        id: get-app-version
        uses: ./.github/actions/get-app-version

      - name: Setup docker image
        id: setup-docker-image
        uses: ./.github/actions/setup-docker-image
        with:
          target: ${{ inputs.image-target }}
          build-args: |
            APP_VERSION=${{ steps.get-app-version.outputs.app-version }}

      - name: Run docker
        shell: bash
        if: ${{ ! inputs.docker-path-to-copy-from }}
        run: |
          docker run --rm -t ${{ steps.setup-docker-image.outputs.image-name }} \
            ${{ inputs.additional-run-args }} \
            ${{ inputs.command }}
