name: Run command in docker container and upload artifact if created

on:
  workflow_call:
    inputs:
      app-version:
        required: true
        type: string
      image-target:
        description: 'The build step target of the docker image'
        type: string
      command:
        description: 'The command to run using the built docker image'
        required: true
      additional-run-args:
        description: 'Any additional args to pass to the docker run subcommand'
      docker-path-to-copy-from:
        description: 'If this is given the contents of the path will be copied to the host'
        required: true
        default: ''
      host-path-to-copy-to:
        description: 'The host path to copy the contents of the docker location specified in the docker-path-to-copy-from arg to'
        required: true

jobs:
  build-docker-image:
    name: Build - docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup docker image
        id: setup-docker-image
        uses: ./.github/actions/setup-docker-image
        with:
          target: ${{ inputs.image-target }}
          build-args: |
            APP_VERSION=${{ inputs.app-version }}

      - name: Run docker with optional file extraction
        shell: bash
        if: ${{ inputs.docker-path-to-copy-from }}
        run: |
          CONTAINER_ID=$( \
            docker create -t ${{ steps.setup-docker-image.outputs.image-name }} \
              ${{ inputs.additional-run-args }} \
              ${{ inputs.command }} \
          )
          docker start -a "$CONTAINER_ID" && exitCode=$? || exitCode=$?
          docker cp "$CONTAINER_ID:${{ inputs.docker-path-to-copy-from }}" \
            ${{ inputs.host-path-to-copy-to }} || true
          exit $exitCode

      - name: Upload artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Mocha maps - screenshots
          path: testing-screenshots
          if-no-files-found: ignore
