name: Build and Deploy Storybook
on: 
  push:
    paths: [".storybook", "src/components/**"]
jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: |
          yarn install
          yarn build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: storybook-dist
          FOLDER: docs-build
          CLEAN: true
          TARGET_FOLDER: docs
